### ISSUE TITLE
Send custome death messages

### ISSUE THREAD

**Issue by H0bbitBaron** [mastercake10/TelegramChat#11]
Hello! Firstly thank you for great plugin)

I have plugin https://www.spigotmc.org/resources/custom-messages.33576/ that modifies messages, especially death ones. I wonder, how can i make TelegramChat use them. I don't know java (python&C only) and tried to play around public void onChat(AsyncPlayerChatEvent e) and e.getMessage() but was unlucky to do what i want. Is there any possibility to get last chat message for example?

Thanks in advance!

**Comment by mastercake10** [comment]
Hey,

I'm not going to support such an "unknown" plugin. Nevertheless, I've added the ability to change the join, quit and death message layout in the config.yml for version 7bbcf58.
