### ISSUE TITLE
Compatibility with ChatControl

### ISSUE THREAD

**Issue by bc-hill** [mastercake10/TelegramChat#13]
I use [ChatControl](https://github.com/kangarko/ChatControl) for filtering, url blocking, etc..
I notice that TelegramChat relays the unfiltered chat, not the output of ChatControl.  For example, I type a blocked word or something, it is blocked in-game, but in Telegram I see the blocked word.

Unsure which plugin needs to address this.

Thank you!

**Comment by bc-hill** [comment]
Developer of ChatControl referenced this [page](https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities)
Adjusting the referenced settings did not resolve this.
Developer of ChatControl advises that this is likely a "major incompatibility"
Thank you.

**Comment by mastercake10** [comment]
You should change the event priority of ChatControl to Lowest in order to archive what you asked for.

**Comment by ghost** [comment]
There wouldn't be any reason to send it to Telegram automatically, if it got cancelled. I tested it with above commit and it works.
