### ISSUE TITLE
Placeholder API support

### ISSUE THREAD

**Issue by Stephirio** [mastercake10/TelegramChat#16]
It would be great to have [PlaceholderApi](https://www.spigotmc.org/resources/placeholderapi.6245/)  inside this plugin. It would be great for example have the [LuckPerms](https://www.spigotmc.org/resources/luckperms.28140/)  prefixes in minecraft-to-telegram chat and in telegram-to-minecraft chat.

**Comment by Scorpionvssub** [comment]
Hello @Stephirio Thank you for the suggestion!
