### ISSUE TITLE
Is it possible to allow the bot to send messages to a group chat?

### ISSUE THREAD

**Issue by ghost** [mastercake10/TelegramChat#22]
I want to make the bot send messages to a public group chat, how do I go around doing that?

**Comment by iCaitlyn** [comment]
Are you unable to just add the bot to the public group chat? That's mostly all I had to do, after initially setting it up as per normal with tokentype.

**Comment by ghost** [comment]
Update: The bot now relays chat messages from minecraft to the Telegram group, but I can't send group messages to Minecraft.
All accounts are linked? (not sure, what does /linktelegram in Telegram do?)

**Comment by iCaitlyn** [comment]
Please read the readme.md on the main project page: Using that command in game gives you a code for which to link accounts with, by sending that code either in the group chat or directly to the bot

**Comment by Rapti** [comment]
I have created a fork that, among other things, allows group chat users to use the bridge without linking their accounts:
https://github.com/Rapti/TelegramChat
The feature is turned off by default though, so you'll need to set `no-link-required: true` in your `config.yml`.

I plan to create a PR soon, but there are some issues I need to fix first.
