### ISSUE TITLE
Plugin keeps reconnecting to Telegram API

### ISSUE THREAD

**Issue by Programie** [mastercake10/TelegramChat#9]
I don't know why, but the plugin keeps reconnecting to the Telegram API all the time even if the Telegram API should work.

I see
```
[Telegram] Established a connection with the telegram servers.
```
every second in the log.

This must be related to the fix in #6.

**Comment by mastercake10** [comment]
Interesting, would like to see more people having this issue before changing anything.

**Comment by H0bbitBaron** [comment]
@mastercake10 same for me:
![image](https://user-images.githubusercontent.com/36517776/36856044-1d615562-1d86-11e8-891e-108821724bcf.png)
